### ISSUE TITLE
Can't seem to install any plugins nor create child theme via sftp

### ISSUE THREAD

**Issue by br0kenlink** [pothi/wp-in-a-box#65]
Hi,
so I tried literally everything,
Every user that your script installs, even enabled root to test.
Can't seem to do anything which involves active sftp/ssh.
Installed plugin to try connecting via ssh, also didn't work.
Any help would be appreciated

**Comment by pothi** [comment]
Hello,

The script requires root privilege to run. WordPress and PHP run as normal user, though. The name of the WordPress / PHP user could be seen in `/root/.envrc` file. You'd see a line with the text "web_developer_username". This is the username that has SFTP privilege. This script only bootstraps the environment for WordPress. It doesn't install WordPress itself. You may need to install WordPress at `/home/web/sites/example.com/public` using the username mentioned in `/root/.envrc' corresponding to `web_developer_username`.

Under what username did you install WordPress and where did you install it?

**Comment by br0kenlink** [comment]
Hi,
yes, i found .envrc. When using provided details, can't connect to server.
I have installed wordpress I think with your script, not sure now. It's located in /var/wordpress/ and owned by nginx user.
What can I do to make it work?

**Comment by pothi** [comment]
> yes, i found .envrc. When using provided details, can't connect to server. Tried sftp on port 21 and 22

Only port 22 is likely to work. Port 21 is never opened by my script. If you can't connect to server, there could be an issue during the installation process. In that case, please check for any errors in the installation log file that can be found at `/root/log/wp-in-a-box.log` . If there are no errors in it, find the server logs (authentication logs) and try to troubleshoot from there.

>  What can I do to make it work?

Irrespective of the script you currently use / installed, the solution is in making sure that the username underwhich PHP runs and the username underwhich the WordPress is installed (or the files are kept) are the same.

For example, you may switch the PHP user to nginx (as WordPress files are owned by nginx user). It isn't a good security practice, though.

Alternatively, find the user of PHP and then switch the ownership of WordPress files to that user.

I hope that helps. If you still can't solve the issues you mentioned and if you are okay in providing the access to your server to me, please feel free to contact me via tinywp.in/contact to have a look into your server's current situation. It is easier for me to fix things on the server than guessing what could've gone wrong without looking at the logs. Thanks.

**Comment by br0kenlink** [comment]
Ah, that's what I have missed.
Was checking file permissions etc but didn't think to check which user runs php-fpm.
Thank you sir, all fixed and works as it should.
