### ISSUE TITLE
Varnish implementation

### ISSUE THREAD

**Issue by chocochrispi** [pothi/wp-in-a-box#78]
I have been using your script pour a while and it's awesome!
We are just missing varnish. Are you planning to implement it anytime soon?
Thanks a lot for your work :)

**Comment by pothi** [comment]
Thanks for testing this script. It's basically a combination of other scripts in Github. I only pulled required component from other scripts.

> We are just missing varnish. Are you planning to implement it anytime soon?

No. Sorry. None of my recent clients are interested in it. So, haven't got a chance to work on it. Varnish definitely has an edge over other methods of caching.

**Comment by chocochrispi** [comment]
Hi Pothi, thank you for your answer! Have a good day
